name: Update `posted_at` automatically
on:
  push:
    paths:
      - "docs/*.md"

jobs:
  update:
    name: Update timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Disable quotepath
        run: git config --local core.quotepath false
      - name: Extract diffs
        uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: "docs/*.md"
      - name: Run sed
        if: env.GIT_DIFF
        run: |
          files=(${{ env.GIT_DIFF }})
          for file in "${files[@]}"; do
            cmd="sed -i '0,/^posted_at:\ .*\$/ s/^posted_at:\ .*\$/posted_at:\ $(TZ=asia/tokyo date "+%Y-%m-%d")/' ${file}"
            eval ${cmd}
          done
      - name: Auto commit
        if: env.GIT_DIFF
        run: |
            git config user.name = "github-actions"
            git config user.email = "github-actions[bot]@users.noreply.github.com"
            git add ${{ env.GIT_DIFF }}
            git commit -m ":robot: Update the date automatically."
            git push origin
